version: "3.0"

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 9000:9000
      - 9229:9229
    command: npm run dev
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:17
    env_file:
      - .development.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
